server:
    port: 8888

spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/gdhi
    host: localhost
    port: 5432
    username: gdhi
    password: password
  jpa:
    showSql: true
    formatSql: true
    hibernate:
      ddlAuto: true
      namingStrategy : org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQL94Dialect

db:
  url: jdbc:postgresql://localhost:5432/gdhi
  host: localhost
  port: 5432
  username: gdhi
  password: password
  driverClassName: org.postgresql.Driver

endpoints.info.id: ping
endpoints.info.sensitive: false
endpoints.info.enabled: true
info.AppName: GDHI-Service
info.Description: Application Health Checker
info.body: pong
info.status: 200
