server:
    port: 8888

flyway:
  enabled: true
  locations: classpath:db.migration
  schemas: [gdhi]

spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/gdhi
    host: localhost
    port: 5432
    username: postgres
    password:

db:
  url: jdbc:postgresql://localhost:5432/gdhi
  host: localhost
  port: 5432
  username: postgres
  password:
  driverClassName: org.postgresql.Driver
